import type { DailyLot, DailyLotFocus } from "./types/dailyLot";

export const DAILY_LOT_NICKNAME_MAX_LENGTH = 20;

export const DAILY_LOT_FOCUS_OPTIONS = [
  "综合",
  "感情",
  "事业/学习",
  "财运",
  "人际",
  "心情",
] as const satisfies readonly DailyLotFocus[];

export const DAILY_LOT_POOL: DailyLot[] = [
  {
    id: "daily-lot-001",
    title: "风起青萍",
    level: "中上签",
    poem: "风来不问归处，心静自有方向。",
    theme: "沉住气",
    keywords: ["等待", "观察", "整理"],
  },
  {
    id: "daily-lot-002",
    title: "竹影临窗",
    level: "中签",
    poem: "竹影摇清昼，虚心纳微光。",
    theme: "留出余地",
    keywords: ["倾听", "弹性", "修正"],
  },
  {
    id: "daily-lot-003",
    title: "春水初生",
    level: "上签",
    poem: "春水初生处，轻舟正可行。",
    theme: "顺势而动",
    keywords: ["开始", "流动", "轻装"],
  },
  {
    id: "daily-lot-004",
    title: "灯下有信",
    level: "中上签",
    poem: "灯下翻旧信，心中见新意。",
    theme: "重新理解",
    keywords: ["复盘", "沟通", "释然"],
  },
  {
    id: "daily-lot-005",
    title: "云开半岭",
    level: "中签",
    poem: "云开未满山，已见半岭青。",
    theme: "逐步明朗",
    keywords: ["耐心", "进展", "确认"],
  },
  {
    id: "daily-lot-006",
    title: "小窗听雨",
    level: "平签",
    poem: "雨声敲小窗，慢处见安稳。",
    theme: "放慢节奏",
    keywords: ["休整", "安定", "觉察"],
  },
  {
    id: "daily-lot-007",
    title: "晨光入盏",
    level: "上签",
    poem: "晨光入茶盏，清气满心怀。",
    theme: "恢复元气",
    keywords: ["清醒", "主动", "温和"],
  },
  {
    id: "daily-lot-008",
    title: "柳暗花微",
    level: "小醒签",
    poem: "柳暗非无路，花微也有香。",
    theme: "别急定论",
    keywords: ["转念", "细看", "缓行"],
  },
  {
    id: "daily-lot-009",
    title: "石上清泉",
    level: "中上签",
    poem: "泉从石上过，久处自成声。",
    theme: "坚持微小",
    keywords: ["积累", "稳定", "专注"],
  },
  {
    id: "daily-lot-010",
    title: "月照归舟",
    level: "中签",
    poem: "月色照归舟，晚风不催人。",
    theme: "照顾自己",
    keywords: ["收束", "休息", "自洽"],
  },
  {
    id: "daily-lot-011",
    title: "松间有路",
    level: "中上签",
    poem: "松间藏细路，行稳见远山。",
    theme: "稳步推进",
    keywords: ["路径", "耐力", "节制"],
  },
  {
    id: "daily-lot-012",
    title: "花影不语",
    level: "平签",
    poem: "花影不争春，自在一枝香。",
    theme: "少些比较",
    keywords: ["自处", "平衡", "安然"],
  },
  {
    id: "daily-lot-013",
    title: "晴檐落雀",
    level: "中签",
    poem: "晴檐落轻雀，小喜在寻常。",
    theme: "看见日常",
    keywords: ["小喜", "陪伴", "松弛"],
  },
  {
    id: "daily-lot-014",
    title: "远钟入梦",
    level: "小醒签",
    poem: "远钟入旧梦，醒来莫久留。",
    theme: "别困旧念",
    keywords: ["放下", "边界", "更新"],
  },
  {
    id: "daily-lot-015",
    title: "溪桥问路",
    level: "中上签",
    poem: "溪桥人未远，问路便逢春。",
    theme: "主动请教",
    keywords: ["询问", "合作", "机会"],
  },
  {
    id: "daily-lot-016",
    title: "白露沾衣",
    level: "平签",
    poem: "白露沾衣角，早行宜添衣。",
    theme: "提前准备",
    keywords: ["计划", "保留", "照护"],
  },
  {
    id: "daily-lot-017",
    title: "兰舟缓渡",
    level: "中签",
    poem: "兰舟缓缓渡，水阔心不慌。",
    theme: "不抢节奏",
    keywords: ["缓和", "秩序", "从容"],
  },
  {
    id: "daily-lot-018",
    title: "山色入怀",
    level: "上签",
    poem: "山色入怀袖，一念天地宽。",
    theme: "打开视野",
    keywords: ["格局", "释放", "开阔"],
  },
  {
    id: "daily-lot-019",
    title: "纸上新墨",
    level: "中上签",
    poem: "新墨落素纸，今日可重写。",
    theme: "重新开始",
    keywords: ["修订", "表达", "行动"],
  },
  {
    id: "daily-lot-020",
    title: "庭前微雪",
    level: "小醒签",
    poem: "微雪覆庭阶，慢行少留痕。",
    theme: "谨慎表达",
    keywords: ["分寸", "谨言", "观察"],
  },
  {
    id: "daily-lot-021",
    title: "茶烟向暖",
    level: "中签",
    poem: "茶烟向暖处，人心可回温。",
    theme: "柔和相处",
    keywords: ["体谅", "修复", "温度"],
  },
  {
    id: "daily-lot-022",
    title: "星河低语",
    level: "中上签",
    poem: "星河虽寂静，暗处有回音。",
    theme: "相信回响",
    keywords: ["回应", "信任", "耐心"],
  },
  {
    id: "daily-lot-023",
    title: "芦花照水",
    level: "平签",
    poem: "芦花照浅水，清浊各分明。",
    theme: "看清关系",
    keywords: ["分辨", "边界", "清理"],
  },
  {
    id: "daily-lot-024",
    title: "青石生苔",
    level: "中签",
    poem: "青石生新苔，旧处也含春。",
    theme: "旧事新解",
    keywords: ["修补", "温习", "生长"],
  },
  {
    id: "daily-lot-025",
    title: "东风解冻",
    level: "上签",
    poem: "东风轻解冻，万物不相催。",
    theme: "机会回暖",
    keywords: ["松动", "契机", "生机"],
  },
  {
    id: "daily-lot-026",
    title: "半卷闲书",
    level: "平签",
    poem: "闲书读半卷，答案在行间。",
    theme: "补足信息",
    keywords: ["学习", "查证", "沉淀"],
  },
  {
    id: "daily-lot-027",
    title: "荷风过岸",
    level: "中上签",
    poem: "荷风过岸来，心事自然清。",
    theme: "情绪疏通",
    keywords: ["坦诚", "舒展", "清明"],
  },
  {
    id: "daily-lot-028",
    title: "暮云知归",
    level: "中签",
    poem: "暮云知归处，人亦识轻重。",
    theme: "明确取舍",
    keywords: ["选择", "优先", "归位"],
  },
  {
    id: "daily-lot-029",
    title: "梅枝含雪",
    level: "小醒签",
    poem: "梅枝含薄雪，香气不急开。",
    theme: "守住分寸",
    keywords: ["克制", "等待", "内敛"],
  },
  {
    id: "daily-lot-030",
    title: "海棠初醒",
    level: "上签",
    poem: "海棠初睡醒，春意已盈门。",
    theme: "状态转好",
    keywords: ["复苏", "自信", "明亮"],
  },
  {
    id: "daily-lot-031",
    title: "一叶知秋",
    level: "小醒签",
    poem: "一叶落掌心，微处见先机。",
    theme: "留意细节",
    keywords: ["信号", "细节", "调整"],
  },
  {
    id: "daily-lot-032",
    title: "云水相逢",
    level: "中上签",
    poem: "云水本无约，相逢自有时。",
    theme: "顺其自然",
    keywords: ["缘分", "松手", "时机"],
  },
  {
    id: "daily-lot-033",
    title: "新晴过巷",
    level: "中签",
    poem: "新晴过窄巷，旧尘渐不扬。",
    theme: "恢复秩序",
    keywords: ["清理", "恢复", "轻盈"],
  },
  {
    id: "daily-lot-034",
    title: "檐铃轻响",
    level: "平签",
    poem: "檐铃轻轻响，提醒在风中。",
    theme: "接收提醒",
    keywords: ["提醒", "专心", "回应"],
  },
  {
    id: "daily-lot-035",
    title: "桂香入夜",
    level: "中上签",
    poem: "桂香入静夜，好意慢慢来。",
    theme: "温柔靠近",
    keywords: ["善意", "靠近", "慢热"],
  },
  {
    id: "daily-lot-036",
    title: "旧径生花",
    level: "上签",
    poem: "旧径忽生花，回看亦成景。",
    theme: "收获显现",
    keywords: ["回报", "欣喜", "确认"],
  },
  {
    id: "daily-lot-037",
    title: "晴湖照影",
    level: "中签",
    poem: "晴湖照人影，心明事自清。",
    theme: "诚实面对",
    keywords: ["自省", "清楚", "坦然"],
  },
  {
    id: "daily-lot-038",
    title: "石径微明",
    level: "中上签",
    poem: "石径微微亮，前行不必急。",
    theme: "找到方向",
    keywords: ["方向", "踏实", "进步"],
  },
  {
    id: "daily-lot-039",
    title: "秋水无尘",
    level: "平签",
    poem: "秋水无多言，清澈胜纷争。",
    theme: "减少争辩",
    keywords: ["安静", "清晰", "退让"],
  },
  {
    id: "daily-lot-040",
    title: "春笺待寄",
    level: "中签",
    poem: "春笺尚未寄，心意可慢陈。",
    theme: "表达心意",
    keywords: ["书写", "沟通", "真诚"],
  },
  {
    id: "daily-lot-041",
    title: "薄雾散阶",
    level: "中上签",
    poem: "薄雾散前阶，近事渐可见。",
    theme: "疑惑减少",
    keywords: ["明朗", "确认", "安心"],
  },
  {
    id: "daily-lot-042",
    title: "炉火微红",
    level: "平签",
    poem: "炉火微微红，小事也可暖。",
    theme: "经营细节",
    keywords: ["细节", "温暖", "维护"],
  },
  {
    id: "daily-lot-043",
    title: "雁过留声",
    level: "小醒签",
    poem: "雁过声犹在，话出要留心。",
    theme: "谨慎沟通",
    keywords: ["表达", "分寸", "回音"],
  },
  {
    id: "daily-lot-044",
    title: "桃枝向阳",
    level: "上签",
    poem: "桃枝向阳处，新意正舒展。",
    theme: "主动生长",
    keywords: ["热情", "展开", "希望"],
  },
  {
    id: "daily-lot-045",
    title: "青灯照案",
    level: "中签",
    poem: "青灯照案前，一笔一事明。",
    theme: "专注处理",
    keywords: ["专注", "条理", "完成"],
  },
  {
    id: "daily-lot-046",
    title: "晚霞留色",
    level: "中上签",
    poem: "晚霞留余色，今日有可记。",
    theme: "珍惜当下",
    keywords: ["感受", "记录", "满足"],
  },
  {
    id: "daily-lot-047",
    title: "溪声绕石",
    level: "中签",
    poem: "溪声绕石去，弯处亦能通。",
    theme: "换个办法",
    keywords: ["变通", "沟通", "耐性"],
  },
  {
    id: "daily-lot-048",
    title: "素月临门",
    level: "平签",
    poem: "素月临门静，少言也安宁。",
    theme: "安静收心",
    keywords: ["收心", "休养", "节制"],
  },
  {
    id: "daily-lot-049",
    title: "梨花带雨",
    level: "小醒签",
    poem: "梨花带雨意，柔处需自珍。",
    theme: "照顾情绪",
    keywords: ["自珍", "情绪", "温柔"],
  },
  {
    id: "daily-lot-050",
    title: "晴岚入袖",
    level: "上签",
    poem: "晴岚入衣袖，好景近身来。",
    theme: "好消息近",
    keywords: ["轻快", "机会", "亲近"],
  },
  {
    id: "daily-lot-051",
    title: "桥边新柳",
    level: "中上签",
    poem: "桥边新柳色，一步一春深。",
    theme: "关系更新",
    keywords: ["连接", "成长", "回应"],
  },
  {
    id: "daily-lot-052",
    title: "夜雨听荷",
    level: "平签",
    poem: "夜雨听荷落，烦心可暂歇。",
    theme: "允许停顿",
    keywords: ["停顿", "安抚", "呼吸"],
  },
  {
    id: "daily-lot-053",
    title: "长街有灯",
    level: "中签",
    poem: "长街灯未灭，归途有人间。",
    theme: "获得支持",
    keywords: ["支持", "陪伴", "安心"],
  },
  {
    id: "daily-lot-054",
    title: "水面微澜",
    level: "小醒签",
    poem: "水面起微澜，心动先问心。",
    theme: "辨认冲动",
    keywords: ["觉察", "冲动", "缓冲"],
  },
  {
    id: "daily-lot-055",
    title: "南窗见日",
    level: "上签",
    poem: "南窗忽见日，阴影自然轻。",
    theme: "心境转亮",
    keywords: ["明朗", "舒心", "转机"],
  },
  {
    id: "daily-lot-056",
    title: "松雪不折",
    level: "中上签",
    poem: "松雪压枝头，枝稳雪自消。",
    theme: "稳住压力",
    keywords: ["承受", "稳定", "化解"],
  },
  {
    id: "daily-lot-057",
    title: "微火煮茶",
    level: "中签",
    poem: "微火煮清茶，慢候味更长。",
    theme: "慢慢经营",
    keywords: ["经营", "耐心", "细水"],
  },
  {
    id: "daily-lot-058",
    title: "疏星照野",
    level: "平签",
    poem: "疏星照旷野，独行也有光。",
    theme: "自我陪伴",
    keywords: ["独处", "勇气", "清醒"],
  },
  {
    id: "daily-lot-059",
    title: "花信迟来",
    level: "小醒签",
    poem: "花信迟迟到，莫把迟当无。",
    theme: "别急催促",
    keywords: ["等待", "信号", "耐心"],
  },
  {
    id: "daily-lot-060",
    title: "朝露映心",
    level: "上签",
    poem: "朝露映初心，清明自生光。",
    theme: "回到初心",
    keywords: ["初心", "清明", "行动"],
  },
];
