import type { TarotCard, TarotSpreadPosition } from "./types/tarot";

export const TAROT_SPREAD_POSITIONS: TarotSpreadPosition[] = [
  {
    index: 1,
    title: "现状",
    description: "你当前所处的状态，以及问题表面下正在发生的事情。",
  },
  {
    index: 2,
    title: "阻碍",
    description: "让事情变得卡住、反复或不够清晰的因素。",
  },
  {
    index: 3,
    title: "建议",
    description: "此刻更适合采取的态度、行动或观察方向。",
  },
];

export const TAROT_CARDS: TarotCard[] = [
  { id: "major-00", name: "愚人", englishName: "The Fool", arcana: "major", suit: "major", keywords: ["开始", "自由", "冒险"] },
  { id: "major-01", name: "魔术师", englishName: "The Magician", arcana: "major", suit: "major", keywords: ["行动", "资源", "创造"] },
  { id: "major-02", name: "女祭司", englishName: "The High Priestess", arcana: "major", suit: "major", keywords: ["直觉", "秘密", "观察"] },
  { id: "major-03", name: "皇后", englishName: "The Empress", arcana: "major", suit: "major", keywords: ["滋养", "丰盛", "关系"] },
  { id: "major-04", name: "皇帝", englishName: "The Emperor", arcana: "major", suit: "major", keywords: ["秩序", "责任", "掌控"] },
  { id: "major-05", name: "教皇", englishName: "The Hierophant", arcana: "major", suit: "major", keywords: ["传统", "规则", "学习"] },
  { id: "major-06", name: "恋人", englishName: "The Lovers", arcana: "major", suit: "major", keywords: ["选择", "吸引", "关系"] },
  { id: "major-07", name: "战车", englishName: "The Chariot", arcana: "major", suit: "major", keywords: ["推进", "意志", "胜利"] },
  { id: "major-08", name: "力量", englishName: "Strength", arcana: "major", suit: "major", keywords: ["耐心", "勇气", "温柔"] },
  { id: "major-09", name: "隐士", englishName: "The Hermit", arcana: "major", suit: "major", keywords: ["独处", "寻找", "沉淀"] },
  { id: "major-10", name: "命运之轮", englishName: "Wheel of Fortune", arcana: "major", suit: "major", keywords: ["转折", "周期", "机会"] },
  { id: "major-11", name: "正义", englishName: "Justice", arcana: "major", suit: "major", keywords: ["平衡", "判断", "因果"] },
  { id: "major-12", name: "倒吊人", englishName: "The Hanged Man", arcana: "major", suit: "major", keywords: ["暂停", "换位", "等待"] },
  { id: "major-13", name: "死神", englishName: "Death", arcana: "major", suit: "major", keywords: ["结束", "转化", "放下"] },
  { id: "major-14", name: "节制", englishName: "Temperance", arcana: "major", suit: "major", keywords: ["调和", "恢复", "节奏"] },
  { id: "major-15", name: "恶魔", englishName: "The Devil", arcana: "major", suit: "major", keywords: ["执念", "束缚", "欲望"] },
  { id: "major-16", name: "高塔", englishName: "The Tower", arcana: "major", suit: "major", keywords: ["冲击", "破局", "醒悟"] },
  { id: "major-17", name: "星星", englishName: "The Star", arcana: "major", suit: "major", keywords: ["希望", "疗愈", "愿景"] },
  { id: "major-18", name: "月亮", englishName: "The Moon", arcana: "major", suit: "major", keywords: ["迷雾", "情绪", "潜意识"] },
  { id: "major-19", name: "太阳", englishName: "The Sun", arcana: "major", suit: "major", keywords: ["明朗", "喜悦", "成功"] },
  { id: "major-20", name: "审判", englishName: "Judgement", arcana: "major", suit: "major", keywords: ["觉醒", "回应", "复盘"] },
  { id: "major-21", name: "世界", englishName: "The World", arcana: "major", suit: "major", keywords: ["完成", "整合", "达成"] },
  { id: "wands-01", name: "权杖一", englishName: "Ace of Wands", arcana: "minor", suit: "wands", keywords: ["灵感", "启动", "热情"] },
  { id: "wands-02", name: "权杖二", englishName: "Two of Wands", arcana: "minor", suit: "wands", keywords: ["规划", "远见", "选择"] },
  { id: "wands-03", name: "权杖三", englishName: "Three of Wands", arcana: "minor", suit: "wands", keywords: ["拓展", "等待", "进展"] },
  { id: "wands-04", name: "权杖四", englishName: "Four of Wands", arcana: "minor", suit: "wands", keywords: ["稳定", "庆祝", "归属"] },
  { id: "wands-05", name: "权杖五", englishName: "Five of Wands", arcana: "minor", suit: "wands", keywords: ["竞争", "摩擦", "磨合"] },
  { id: "wands-06", name: "权杖六", englishName: "Six of Wands", arcana: "minor", suit: "wands", keywords: ["认可", "胜利", "曝光"] },
  { id: "wands-07", name: "权杖七", englishName: "Seven of Wands", arcana: "minor", suit: "wands", keywords: ["防守", "坚持", "立场"] },
  { id: "wands-08", name: "权杖八", englishName: "Eight of Wands", arcana: "minor", suit: "wands", keywords: ["加速", "消息", "推进"] },
  { id: "wands-09", name: "权杖九", englishName: "Nine of Wands", arcana: "minor", suit: "wands", keywords: ["戒备", "韧性", "疲惫"] },
  { id: "wands-10", name: "权杖十", englishName: "Ten of Wands", arcana: "minor", suit: "wands", keywords: ["压力", "责任", "负担"] },
  { id: "wands-page", name: "权杖侍从", englishName: "Page of Wands", arcana: "minor", suit: "wands", keywords: ["好奇", "探索", "消息"] },
  { id: "wands-knight", name: "权杖骑士", englishName: "Knight of Wands", arcana: "minor", suit: "wands", keywords: ["冲劲", "变化", "冒进"] },
  { id: "wands-queen", name: "权杖王后", englishName: "Queen of Wands", arcana: "minor", suit: "wands", keywords: ["自信", "魅力", "主动"] },
  { id: "wands-king", name: "权杖国王", englishName: "King of Wands", arcana: "minor", suit: "wands", keywords: ["领导", "愿景", "掌控"] },
  { id: "cups-01", name: "圣杯一", englishName: "Ace of Cups", arcana: "minor", suit: "cups", keywords: ["情感", "开启", "流动"] },
  { id: "cups-02", name: "圣杯二", englishName: "Two of Cups", arcana: "minor", suit: "cups", keywords: ["连接", "吸引", "合作"] },
  { id: "cups-03", name: "圣杯三", englishName: "Three of Cups", arcana: "minor", suit: "cups", keywords: ["庆祝", "朋友", "支持"] },
  { id: "cups-04", name: "圣杯四", englishName: "Four of Cups", arcana: "minor", suit: "cups", keywords: ["冷淡", "犹豫", "错过"] },
  { id: "cups-05", name: "圣杯五", englishName: "Five of Cups", arcana: "minor", suit: "cups", keywords: ["失落", "遗憾", "修复"] },
  { id: "cups-06", name: "圣杯六", englishName: "Six of Cups", arcana: "minor", suit: "cups", keywords: ["回忆", "旧人", "单纯"] },
  { id: "cups-07", name: "圣杯七", englishName: "Seven of Cups", arcana: "minor", suit: "cups", keywords: ["幻想", "选择", "混乱"] },
  { id: "cups-08", name: "圣杯八", englishName: "Eight of Cups", arcana: "minor", suit: "cups", keywords: ["离开", "寻找", "转身"] },
  { id: "cups-09", name: "圣杯九", englishName: "Nine of Cups", arcana: "minor", suit: "cups", keywords: ["满足", "愿望", "享受"] },
  { id: "cups-10", name: "圣杯十", englishName: "Ten of Cups", arcana: "minor", suit: "cups", keywords: ["圆满", "家庭", "幸福"] },
  { id: "cups-page", name: "圣杯侍从", englishName: "Page of Cups", arcana: "minor", suit: "cups", keywords: ["心动", "表达", "敏感"] },
  { id: "cups-knight", name: "圣杯骑士", englishName: "Knight of Cups", arcana: "minor", suit: "cups", keywords: ["浪漫", "邀约", "理想"] },
  { id: "cups-queen", name: "圣杯王后", englishName: "Queen of Cups", arcana: "minor", suit: "cups", keywords: ["共情", "温柔", "直觉"] },
  { id: "cups-king", name: "圣杯国王", englishName: "King of Cups", arcana: "minor", suit: "cups", keywords: ["成熟", "克制", "包容"] },
  { id: "swords-01", name: "宝剑一", englishName: "Ace of Swords", arcana: "minor", suit: "swords", keywords: ["清晰", "真相", "决断"] },
  { id: "swords-02", name: "宝剑二", englishName: "Two of Swords", arcana: "minor", suit: "swords", keywords: ["僵持", "回避", "选择"] },
  { id: "swords-03", name: "宝剑三", englishName: "Three of Swords", arcana: "minor", suit: "swords", keywords: ["刺痛", "分离", "释放"] },
  { id: "swords-04", name: "宝剑四", englishName: "Four of Swords", arcana: "minor", suit: "swords", keywords: ["休息", "恢复", "暂停"] },
  { id: "swords-05", name: "宝剑五", englishName: "Five of Swords", arcana: "minor", suit: "swords", keywords: ["冲突", "输赢", "消耗"] },
  { id: "swords-06", name: "宝剑六", englishName: "Six of Swords", arcana: "minor", suit: "swords", keywords: ["过渡", "离开", "修复"] },
  { id: "swords-07", name: "宝剑七", englishName: "Seven of Swords", arcana: "minor", suit: "swords", keywords: ["隐藏", "策略", "逃避"] },
  { id: "swords-08", name: "宝剑八", englishName: "Eight of Swords", arcana: "minor", suit: "swords", keywords: ["限制", "焦虑", "困住"] },
  { id: "swords-09", name: "宝剑九", englishName: "Nine of Swords", arcana: "minor", suit: "swords", keywords: ["担忧", "失眠", "内耗"] },
  { id: "swords-10", name: "宝剑十", englishName: "Ten of Swords", arcana: "minor", suit: "swords", keywords: ["结束", "低谷", "翻篇"] },
  { id: "swords-page", name: "宝剑侍从", englishName: "Page of Swords", arcana: "minor", suit: "swords", keywords: ["观察", "消息", "警觉"] },
  { id: "swords-knight", name: "宝剑骑士", englishName: "Knight of Swords", arcana: "minor", suit: "swords", keywords: ["直接", "冲刺", "急躁"] },
  { id: "swords-queen", name: "宝剑王后", englishName: "Queen of Swords", arcana: "minor", suit: "swords", keywords: ["理性", "边界", "洞察"] },
  { id: "swords-king", name: "宝剑国王", englishName: "King of Swords", arcana: "minor", suit: "swords", keywords: ["判断", "规则", "权威"] },
  { id: "pentacles-01", name: "星币一", englishName: "Ace of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["机会", "现实", "开始"] },
  { id: "pentacles-02", name: "星币二", englishName: "Two of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["平衡", "调度", "变化"] },
  { id: "pentacles-03", name: "星币三", englishName: "Three of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["协作", "技能", "建设"] },
  { id: "pentacles-04", name: "星币四", englishName: "Four of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["保守", "掌控", "安全"] },
  { id: "pentacles-05", name: "星币五", englishName: "Five of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["匮乏", "支持", "低潮"] },
  { id: "pentacles-06", name: "星币六", englishName: "Six of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["给予", "互助", "公平"] },
  { id: "pentacles-07", name: "星币七", englishName: "Seven of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["等待", "评估", "投入"] },
  { id: "pentacles-08", name: "星币八", englishName: "Eight of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["打磨", "专注", "学习"] },
  { id: "pentacles-09", name: "星币九", englishName: "Nine of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["独立", "收获", "品质"] },
  { id: "pentacles-10", name: "星币十", englishName: "Ten of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["积累", "家庭", "长期"] },
  { id: "pentacles-page", name: "星币侍从", englishName: "Page of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["学习", "机会", "务实"] },
  { id: "pentacles-knight", name: "星币骑士", englishName: "Knight of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["稳步", "耐心", "执行"] },
  { id: "pentacles-queen", name: "星币王后", englishName: "Queen of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["照顾", "稳定", "丰足"] },
  { id: "pentacles-king", name: "星币国王", englishName: "King of Pentacles", arcana: "minor", suit: "pentacles", keywords: ["资源", "成熟", "经营"] },
];

export const TAROT_QUESTION_MIN_LENGTH = 4;
export const TAROT_QUESTION_MAX_LENGTH = 100;
