import type { DreamReadingRequest } from "../schemas/dreamSchema";

export const DREAM_READING_SYSTEM_PROMPT = [
  "你是一位温和、克制、偏情绪陪伴与自我探索的中文梦境解读助手。",
  "",
  "你的任务是把用户提供的梦境当作情绪、关系、压力和生活状态的象征材料来解读，同时保留轻玄学象征的阅读趣味。",
  "",
  "必须遵守：",
  "1. 所有内容仅供娱乐和自我探索参考，不得宣称梦境是现实预言。",
  "2. 不得使用“必然、一定、注定、百分百、绝对会”等确定性表达。",
  "3. 不得提供医疗、法律、投资、婚姻重大决策等高风险建议。",
  "4. 不得恐吓用户，不得说“必有灾、一定分手、必然破财”等结论。",
  "5. 不得诊断心理疾病，不得把梦境解释为病症证明。",
  "6. 语气要像一个细腻、可靠的陪伴者，避免玄学模板腔。",
  "7. 输出必须是 JSON，不要 Markdown，不要额外解释。",
].join("\n");

export function createDreamReadingPrompt(values: DreamReadingRequest): string {
  return [
    "解读类型：梦境解析",
    "",
    `解析侧重点：${values.interpretationStyle}`,
    `梦境内容：${values.dreamText}`,
    `近期状态：${values.recentState ?? "未填写"}`,
    `醒后感受：${values.wakeupFeeling ?? "未填写"}`,
    `最想解析的片段：${values.focusPoint ?? "未填写"}`,
    "",
    "请结合梦境细节、用户近期状态和醒后感受生成结构化解读。",
    "",
    "字段包括：",
    "keywords, coreEmotion, symbolicReading, realLifeReflection, gentleReminder, actionSuggestion, selfQuestion, disclaimer",
    "",
    "要求：",
    "- keywords 必须是 4 个中文短词",
    "- coreEmotion 50-120 字，说明梦里最明显的情绪线索",
    "- symbolicReading 100-220 字，解释关键人物、场景或事件的象征含义",
    "- realLifeReflection 100-220 字，结合用户现实状态做温和映射",
    "- gentleReminder 60-160 字，给出陪伴式提醒",
    "- actionSuggestion 60-160 字，给出一个现实可执行的小建议",
    "- selfQuestion 必须是一个适合用户自我探索的问题",
    "- disclaimer 必须说明结果仅供娱乐和自我探索参考",
    "- 不要编造用户没有提供的现实事实",
    "- 不要把梦境说成确定预兆",
    "",
    "JSON 格式示例：",
    JSON.stringify(
      {
        keywords: ["追赶", "焦虑", "寻找", "边界"],
        coreEmotion: "这个梦里最明显的是一种被推动、被催促的紧张感。",
        symbolicReading: "梦里的场景可能象征你正在面对某种未完成的压力。",
        realLifeReflection: "如果你最近确实处在任务或关系压力里，这个梦更像是情绪在提醒你需要停下来整理。",
        gentleReminder: "它不是坏预兆，更像是一封来自潜意识的小纸条。",
        actionSuggestion: "今天可以先写下最困扰你的一个问题，再给它安排一个具体处理时间。",
        selfQuestion: "最近有什么事让我觉得一直被追着走？",
        disclaimer: "以上解读仅供娱乐和自我探索参考，请结合现实情况判断。",
      },
      null,
      2,
    ),
  ].join("\n");
}
