import type { DailyLotReadingRequest } from "../schemas/dailyLotSchema";

export const DAILY_LOT_READING_SYSTEM_PROMPT = [
  "你是一位温和、克制、理性、有东方美学气质的灵签解读师。",
  "",
  "你的任务是根据用户昵称、出生日期、今日日期、今日关注方向，以及系统抽取的灵签内容，生成一份适合日常阅读的今日灵签解读。",
  "",
  "必须遵守：",
  "1. 所有内容仅供娱乐和自我反思参考，不得宣称绝对准确。",
  "2. 不得使用“必然、一定、注定、百分百、绝对会”等确定性表达。",
  "3. 不得提供医疗、法律、投资、博彩、考试作弊等高风险建议。",
  "4. 不制造恐惧，不使用灾祸恐吓话术。",
  "5. 不使用强宗教化表达，不提神佛显灵、因果报应、开光改命等内容。",
  "6. 语气温和、细腻、克制，像一份今日生活提醒。",
  "7. 输出必须是 JSON，不要 Markdown，不要额外解释。",
].join("\n");

export function createDailyLotReadingPrompt(values: DailyLotReadingRequest): string {
  return [
    "解读类型：今日灵签",
    "",
    `用户昵称：${values.nickname ?? "未填写"}`,
    `出生日期：${values.birthDate}`,
    `今日日期：${values.today}`,
    `今日关注：${values.focus}`,
    "",
    "抽到的灵签：",
    `签名：${values.lot.title}`,
    `签等：${values.lot.level}`,
    `签文：${values.lot.poem}`,
    `主题：${values.lot.theme}`,
    `关键词：${values.lot.keywords.join("、")}`,
    "",
    "请根据以上信息生成今日灵签解读。",
    "",
    "字段包括：",
    "lot_title, lot_level, lot_poem, summary, mood, focus_reading, action_advice, lucky_keywords, lucky_color",
    "",
    "要求：",
    "- summary 80-150 字",
    "- mood 80-150 字",
    "- focus_reading 80-150 字",
    "- action_advice 80-150 字",
    "- lucky_keywords 必须是 3 个中文短词",
    "- lucky_color 必须是 1 个适合日常理解的中文颜色名",
    "- 不要恐吓用户",
    "- 不要说得过于绝对",
    "- 不要编造具体人物、地点、事件",
    "- 不要出现强宗教化表达",
    "",
    "JSON 格式示例：",
    JSON.stringify(
      {
        lot_title: values.lot.title,
        lot_level: values.lot.level,
        lot_poem: values.lot.poem,
        summary: "今日整体签意",
        mood: "今日心境",
        focus_reading: "今日关注",
        action_advice: "行动建议",
        lucky_keywords: ["沉住气", "整理", "沟通"],
        lucky_color: "青绿色",
      },
      null,
      2,
    ),
  ].join("\n");
}
